---
- hosts: prod
  become: true
  tasks:

  - name: Update all Ubuntu packages
    apt:
      upgrade: "dist"
    when: ansible_distribution == 'Ubuntu'

  - name: Install required Ubuntu packages
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - openjdk-8-jdk

  - name: Install prerequisites for Docker repository
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
      update_cache: yes

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes
